/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/plants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get all plants
		 * @description Retrieve all plants belonging to the authenticated user
		 */
		get: operations['getPlants'];
		put?: never;
		/**
		 * Create a new plant
		 * @description Create a new plant for the authenticated user with auto-generated slug
		 */
		post: operations['createPlant'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/plants/slug/{slug}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		/**
		 * Get plant by slug
		 * @description Retrieve a specific plant by its slug. Only returns plants belonging to the authenticated user.
		 */
		get: operations['getPlantBySlug'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/plants/water': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Mark plants as watered
		 * @description Bulk operation to mark multiple plants as watered. Updates lastWatered timestamp to current time.
		 */
		post: operations['waterPlants'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/plants/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete a plant
		 * @description Delete a plant belonging to the authenticated user
		 */
		delete: operations['deletePlant'];
		options?: never;
		head?: never;
		/**
		 * Update a plant
		 * @description Update an existing plant. Only the provided fields will be updated.
		 */
		patch: operations['updatePlant'];
		trace?: never;
	};
	'/api/notifications': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get notification configuration
		 * @description Retrieve notification configuration for the authenticated user. Returns default config if none exists.
		 */
		get: operations['getNotificationConfig'];
		/**
		 * Create or update notification configuration
		 * @description Create or update notification configuration for the authenticated user
		 */
		put: operations['upsertNotificationConfig'];
		post?: never;
		/**
		 * Delete notification configuration
		 * @description Delete notification configuration for the authenticated user
		 */
		delete: operations['deleteNotificationConfig'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @enum {string} */
		SunlightRequirement: SunlightRequirement;
		/** @enum {string} */
		WateringMethod: WateringMethod;
		/** @enum {string} */
		WaterType: WaterType;
		/** @enum {string} */
		FertilizerType: FertilizerType;
		/** @enum {string} */
		PestType: PestType;
		/** @enum {string} */
		PestStatus: PestStatus;
		/** @enum {string} */
		PlantFlag: PlantFlag;
		/** @enum {string} */
		HealthStatus: HealthStatus;
		Location: {
			/** @example Living Room */
			room: string;
			/** @example Window Sill */
			position: string;
			/** @example false */
			isOutdoors: boolean;
		};
		WateringConfig: {
			/** @example 7 */
			intervalDays: number;
			method: components['schemas']['WateringMethod'];
			waterType: components['schemas']['WaterType'];
			/** Format: date-time */
			lastWatered?: string | null;
		};
		HumidityConfig: {
			/** @example true */
			requiresMisting: boolean;
			/** @example 2 */
			mistingIntervalDays: number;
			/** Format: date-time */
			lastMisted?: string | null;
			/** @example false */
			requiresHumidifier: boolean;
			/**
			 * Format: double
			 * @example 60
			 */
			targetHumidityPct: number;
		};
		FertilizerConfig: {
			type: components['schemas']['FertilizerType'];
			/** @example 14 */
			intervalDays: number;
			/** @example 10:10:10 */
			npkRatio: string;
			/**
			 * Format: double
			 * @example 50
			 */
			concentrationPercent: number;
			/** Format: date-time */
			lastFertilized?: string | null;
			/** @example false */
			activeInWinter: boolean;
		};
		SoilConfig: {
			/** @example Well-draining */
			type: string;
			/**
			 * @example [
			 *       "Peat",
			 *       "Perlite",
			 *       "Bark"
			 *     ]
			 */
			components: string[];
			/** Format: date-time */
			lastRepotted?: string | null;
			/** @example 2 */
			repottingCycle: number;
		};
		SeasonalAdjustments: {
			/** @example true */
			winterRestPeriod: boolean;
			/**
			 * Format: double
			 * @example 0.5
			 */
			winterWaterFactor: number;
			/**
			 * Format: double
			 * @example 15
			 */
			minTempCelsius: number;
		};
		PestInfection: {
			id: string;
			pest: components['schemas']['PestType'];
			/** Format: date-time */
			detectedAt: string;
			/** Format: date-time */
			resolvedAt?: string | null;
			status: components['schemas']['PestStatus'];
			/** @example Neem oil spray */
			treatment: string;
			/** @example Applied weekly treatment */
			notes: string;
		};
		GrowthLog: {
			id: string;
			/** Format: date-time */
			date: string;
			/**
			 * Format: double
			 * @example 45.5
			 */
			heightCm: number;
			/** @example 12 */
			leafCount: number;
			health: components['schemas']['HealthStatus'];
			/** @example New leaf unfurling */
			condition: string;
			photoId: string;
		};
		Plant: {
			/** @description Unique plant identifier */
			id: string;
			/** @description Owner's user ID */
			userId: string;
			/**
			 * @description URL-friendly unique slug
			 * @example monstera-deliciosa
			 */
			slug: string;
			/** @example Monstera Deliciosa */
			name: string;
			/** @example Monstera deliciosa */
			species: string;
			/** @example true */
			isToxic: boolean;
			sunlight?: components['schemas']['SunlightRequirement'] | null;
			/**
			 * Format: double
			 * @example 22
			 */
			preferedTemperature: number;
			location?: components['schemas']['Location'] | null;
			watering?: components['schemas']['WateringConfig'] | null;
			fertilizing?: components['schemas']['FertilizerConfig'];
			humidity?: components['schemas']['HumidityConfig'];
			soil?: components['schemas']['SoilConfig'];
			seasonality?: components['schemas']['SeasonalAdjustments'];
			pestHistory: components['schemas']['PestInfection'][];
			flags: components['schemas']['PlantFlag'][];
			notes: string[];
			photoIds: string[];
			growthHistory: components['schemas']['GrowthLog'][];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CreatePlantRequest: {
			/** @example Monstera Deliciosa */
			name: string;
			/** @example Monstera deliciosa */
			species?: string;
			/** @example true */
			isToxic: boolean;
			sunlight?: components['schemas']['SunlightRequirement'] | null;
			/**
			 * Format: double
			 * @example 22
			 */
			preferedTemperature: number;
			location?: components['schemas']['Location'] | null;
			watering?: components['schemas']['WateringConfig'] | null;
			fertilizing?: components['schemas']['FertilizerConfig'] | null;
			humidity?: components['schemas']['HumidityConfig'] | null;
			soil?: components['schemas']['SoilConfig'] | null;
			seasonality?: components['schemas']['SeasonalAdjustments'] | null;
			pestHistory: components['schemas']['PestInfection'][];
			flags: components['schemas']['PlantFlag'][];
			notes: string[];
			photoIds: string[];
			growthHistory: components['schemas']['GrowthLog'][];
		};
		/** @description All fields are optional. Only provided fields will be updated. */
		UpdatePlantRequest: {
			name?: string;
			species?: string;
			isToxic?: boolean;
			sunlight?: components['schemas']['SunlightRequirement'];
			/** Format: double */
			preferedTemperature?: number;
			location?: components['schemas']['Location'];
			watering?: components['schemas']['WateringConfig'];
			fertilizing?: components['schemas']['FertilizerConfig'];
			humidity?: components['schemas']['HumidityConfig'];
			soil?: components['schemas']['SoilConfig'];
			seasonality?: components['schemas']['SeasonalAdjustments'];
			pestHistory?: components['schemas']['PestInfection'][];
			flags?: components['schemas']['PlantFlag'][];
			notes?: string[];
			photoIds?: string[];
			growthHistory?: components['schemas']['GrowthLog'][];
		};
		QuietHours: {
			/**
			 * @description Start time in HH:mm format
			 * @example 22:00
			 */
			start: string;
			/**
			 * @description End time in HH:mm format
			 * @example 07:00
			 */
			end: string;
		};
		NotificationConfig: {
			/** @description Configuration ID */
			id: string;
			/** @description Owner's user ID */
			userId: string;
			/**
			 * @description Global notification enable/disable
			 * @example true
			 */
			isEnabled: boolean;
			/**
			 * @description Preferred time for notifications in HH:mm format
			 * @example 08:00
			 */
			preferredTime: string;
			quietHours?: components['schemas']['QuietHours'];
			/**
			 * @description 0 = immediate, 1 = daily batching, etc.
			 * @example 1
			 */
			batchingDays: number;
			/**
			 * @description Group notifications by type (watering, fertilizing, etc.)
			 * @example true
			 */
			groupByType: boolean;
			/** @description Plant IDs that should never send notifications */
			mutedPlantIds: string[];
			/** @example true */
			remindWatering: boolean;
			/** @example true */
			remindFertilize: boolean;
			/** @example true */
			remindRepotting: boolean;
			/** @example true */
			remindMisting: boolean;
			/** Format: date-time */
			updatedAt: string;
		};
		NotificationConfigInput: {
			/** @example true */
			isEnabled: boolean;
			/** @example 08:00 */
			preferredTime: string;
			quietHours?: components['schemas']['QuietHours'];
			/** @example 1 */
			batchingDays: number;
			/** @example true */
			groupByType: boolean;
			mutedPlantIds: string[];
			/** @example true */
			remindWatering: boolean;
			/** @example true */
			remindFertilize: boolean;
			/** @example true */
			remindRepotting: boolean;
			/** @example true */
			remindMisting: boolean;
		};
		ValidationError: {
			/** @example name */
			field?: string;
			/** @example Name is required */
			message?: string;
		};
		ErrorResponse: {
			message?: string;
			errors?: components['schemas']['ValidationError'][];
		};
	};
	responses: {
		/** @description Unauthorized - Invalid or missing authentication token */
		Unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': {
					/** @example Unauthorized */
					message?: string;
				};
			};
		};
		/** @description Resource not found */
		NotFound: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': {
					/** @example Not Found */
					message?: string;
				};
			};
		};
		/** @description Validation error */
		ValidationError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': components['schemas']['ErrorResponse'];
			};
		};
		/** @description Internal server error */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				'application/json': {
					/** @example Internal server error */
					message?: string;
				};
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type Location = components['schemas']['Location'];
export type WateringConfig = components['schemas']['WateringConfig'];
export type HumidityConfig = components['schemas']['HumidityConfig'];
export type FertilizerConfig = components['schemas']['FertilizerConfig'];
export type SoilConfig = components['schemas']['SoilConfig'];
export type SeasonalAdjustments = components['schemas']['SeasonalAdjustments'];
export type PestInfection = components['schemas']['PestInfection'];
export type GrowthLog = components['schemas']['GrowthLog'];
export type Plant = components['schemas']['Plant'];
export type CreatePlantRequest = components['schemas']['CreatePlantRequest'];
export type UpdatePlantRequest = components['schemas']['UpdatePlantRequest'];
export type QuietHours = components['schemas']['QuietHours'];
export type NotificationConfig = components['schemas']['NotificationConfig'];
export type NotificationConfigInput = components['schemas']['NotificationConfigInput'];
export type ValidationError = components['schemas']['ValidationError'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseValidationError = components['responses']['ValidationError'];
export type ResponseInternalError = components['responses']['InternalError'];
export type $defs = Record<string, never>;
export interface operations {
	getPlants: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Plant'][];
				};
			};
			401: components['responses']['Unauthorized'];
			500: components['responses']['InternalError'];
		};
	};
	createPlant: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreatePlantRequest'];
			};
		};
		responses: {
			/** @description Plant created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Plant'];
				};
			};
			400: components['responses']['ValidationError'];
			401: components['responses']['Unauthorized'];
			500: components['responses']['InternalError'];
		};
	};
	getPlantBySlug: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/**
				 * @description URL-friendly slug of the plant
				 * @example monstera-deliciosa
				 */
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Plant'];
				};
			};
			401: components['responses']['Unauthorized'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	waterPlants: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/**
					 * @description Array of plant IDs to mark as watered
					 * @example [
					 *       "507f1f77bcf86cd799439011",
					 *       "507f191e810c19729de860ea"
					 *     ]
					 */
					plantIds: string[];
				};
			};
		};
		responses: {
			/** @description Plants watered successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example true */
						success?: boolean;
					};
				};
			};
			400: components['responses']['ValidationError'];
			401: components['responses']['Unauthorized'];
			500: components['responses']['InternalError'];
		};
	};
	deletePlant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Plant ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Plant deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example true */
						success?: boolean;
					};
				};
			};
			401: components['responses']['Unauthorized'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	updatePlant: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Plant ID */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdatePlantRequest'];
			};
		};
		responses: {
			/** @description Plant updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Plant'];
				};
			};
			400: components['responses']['ValidationError'];
			401: components['responses']['Unauthorized'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
	getNotificationConfig: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NotificationConfig'];
				};
			};
			401: components['responses']['Unauthorized'];
			500: components['responses']['InternalError'];
		};
	};
	upsertNotificationConfig: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['NotificationConfigInput'];
			};
		};
		responses: {
			/** @description Configuration updated successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NotificationConfig'];
				};
			};
			/** @description Configuration created successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NotificationConfig'];
				};
			};
			400: components['responses']['ValidationError'];
			401: components['responses']['Unauthorized'];
			500: components['responses']['InternalError'];
		};
	};
	deleteNotificationConfig: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Configuration deleted successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						/** @example true */
						success?: boolean;
					};
				};
			};
			401: components['responses']['Unauthorized'];
			404: components['responses']['NotFound'];
			500: components['responses']['InternalError'];
		};
	};
}
export enum SunlightRequirement {
	Full_Sun = 'Full Sun',
	Indirect_Sun = 'Indirect Sun',
	Partial_Shade = 'Partial Shade',
	Partial_to_Full_Shade = 'Partial to Full Shade',
	Full_Shade = 'Full Shade'
}
export enum WateringMethod {
	Top = 'Top',
	Bottom = 'Bottom',
	Soaking = 'Soaking',
	Self = 'Self',
	MistingOnly = 'MistingOnly'
}
export enum WaterType {
	Tap = 'Tap',
	Filtered = 'Filtered',
	Rain = 'Rain',
	Distilled = 'Distilled',
	StaleTap = 'StaleTap',
	LowLimestone = 'LowLimestone'
}
export enum FertilizerType {
	Liquid = 'Liquid',
	Sticks = 'Sticks',
	Granulate = 'Granulate',
	LongTerm = 'LongTerm',
	Organic = 'Organic',
	Hydroponic = 'Hydroponic'
}
export enum PestType {
	Spider_Mites = 'Spider Mites',
	Aphids = 'Aphids',
	Thrips = 'Thrips',
	Mealybugs = 'Mealybugs',
	Scale = 'Scale',
	Fungus_Gnats = 'Fungus Gnats',
	Root_Rot = 'Root Rot'
}
export enum PestStatus {
	Active = 'Active',
	Treated = 'Treated',
	Resolved = 'Resolved'
}
export enum PlantFlag {
	No_Draught = 'No Draught',
	Remove_Brown_Leaves = 'Remove Brown Leaves',
	High_Humidity_Required = 'High Humidity Required',
	Sensitive_Roots = 'Sensitive Roots'
}
export enum HealthStatus {
	Excellent = 'Excellent',
	Good = 'Good',
	Fair = 'Fair',
	Poor = 'Poor',
	Dormant = 'Dormant'
}
